[".config/ghostty/themes"]
  type = "archive"
  url = "https://github.com/catppuccin/ghostty/archive/refs/heads/main.zip"
  include = ["*/themes/**"]
  refreshPeriod = "168h"
  stripComponents = 2

[".config/tmux/plugins/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/tmux/archive/master.tar.gz"
  exact = true
  refreshPeriod = "168h"
  stripComponents = 1
